name: Criar nota e enviar para repo privado

on:
  push:
    branches:
      - main

jobs:
  generate_note:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório público
        uses: actions/checkout@v3

      - name: Criar nota Markdown
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          NOTE_FILE="note-$TIMESTAMP.md"
          echo "## Nova atualização em $TIMESTAMP" > $NOTE_FILE
          echo "- **Autor:** $(git log -1 --pretty=format:'%an')" >> $NOTE_FILE
          echo "- **Mensagem:** $(git log -1 --pretty=format:'%s')" >> $NOTE_FILE
          echo "- **Commit:** [$(git log -1 --pretty=format:'%H')](https://github.com/hugosousa42/Zettelkasten/commit/$(git log -1 --pretty=format:'%H'))" >> $NOTE_FILE
          echo "- **Data do Commit:** $(git log -1 --pretty=format:'%cd')" >> $NOTE_FILE
          echo "### Diferenças do Commit:" >> $NOTE_FILE
          git diff-tree -r --no-commit-id --name-only HEAD | while read filename; do
            echo "```diff" >> $NOTE_FILE
            git diff -p HEAD^ HEAD -- "$filename" >> $NOTE_FILE
            echo "```" >> $NOTE_FILE
          done

      - name: Clonar o repositório privado e enviar nota
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/hugosousa42/Zettelkasten.git
          cd Zettelkasten
          mv ../note-*.md .

          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"

          git add .

          # Evita erro caso não haja mudanças
          if git diff --staged --quiet; then
            echo "Nenhuma mudança detectada. Pulando commit."
            exit 0
          fi

          git commit -m "Adicionando nova nota automática"
          git push
